# -*- coding: utf-8 -*-
"""CumulativeSumAndProduct.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QtIsG_hUyQVIxCYot93A3DHS_wCilAat
"""

# Cumulative Sum and Product
import pandas as pd

# Creating a DataFrame
data = {'Sales': [100, 200, 150, 300, 250]}
df = pd.DataFrame(data)

# Calculating cumulative sum and product
df['Cumulative Sum'] = df['Sales'].cumsum()
df['Cumulative Product'] = df['Sales'].cumprod()

print('DataFrame with Cumulative Operations:\n', df)