# -*- coding: utf-8 -*-
"""CustomAggregationsGroupby.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QtIsG_hUyQVIxCYot93A3DHS_wCilAat
"""

# Creating Custom Aggregations with Groupby
import pandas as pd

# Creating a DataFrame
data = {'Category': ['A', 'A', 'B', 'B'], 'Value': [10, 20, 30, 40]}
df = pd.DataFrame(data)

# Using groupby with custom aggregation
custom_agg = df.groupby('Category').agg(max_value=('Value', 'max'), min_value=('Value', 'min'))

print('Custom Aggregation Result:\n', custom_agg)