# -*- coding: utf-8 -*-
"""CutForBinningData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QtIsG_hUyQVIxCYot93A3DHS_wCilAat
"""

# Using pd.cut for Binning Data
import pandas as pd

# Creating a DataFrame
data = {'Scores': [50, 60, 70, 80, 90, 100]}
df = pd.DataFrame(data)

# Binning the scores into categories
df['Grade'] = pd.cut(df['Scores'], bins=[0, 59, 69, 79, 89, 100], labels=['F', 'D', 'C', 'B', 'A'])

print('DataFrame with Binned Scores:\n', df)