# -*- coding: utf-8 -*-
"""DataFrameInfoAndMemory Usage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QtIsG_hUyQVIxCYot93A3DHS_wCilAat
"""

#  DataFrame Info and Memory Usage
import pandas as pd

# Creating a DataFrame
data = {'A': range(1000), 'B': range(1000, 2000)}
df = pd.DataFrame(data)

# Displaying DataFrame info and memory usage
df_info = df.info(memory_usage='deep')

print('DataFrame Info and Memory Usage:', df_info)

