# -*- coding: utf-8 -*-
"""DropDuplicates.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QtIsG_hUyQVIxCYot93A3DHS_wCilAat
"""

# Using drop_duplicates() for Unique Rows
import pandas as pd

# Creating a DataFrame with duplicate rows
data = {'Name': ['Alice', 'Bob', 'Alice', 'Charlie'], 'Score': [85, 70, 85, 95]}
df = pd.DataFrame(data)

# Dropping duplicate rows
unique_df = df.drop_duplicates()

print('DataFrame after Dropping Duplicates:\n', unique_df)