# -*- coding: utf-8 -*-
"""MeltingDataFrames.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QtIsG_hUyQVIxCYot93A3DHS_wCilAat
"""

#  Melting DataFrames
import pandas as pd

# Creating a DataFrame
data = {'ID': [1, 2], 'Math': [90, 80], 'Science': [85, 88]}
df = pd.DataFrame(data)

# Melting the DataFrame
melted_df = pd.melt(df, id_vars=['ID'], value_vars=['Math', 'Science'], var_name='Subject', value_name='Score')

print('Melted DataFrame:\n', melted_df)

