# -*- coding: utf-8 -*-
"""SettingAndResettingIndexes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QtIsG_hUyQVIxCYot93A3DHS_wCilAat
"""

# Setting and Resetting Indexes
import pandas as pd

# Creating a DataFrame
data = {'City': ['NY', 'LA', 'SF'], 'Year': [2020, 2021, 2021], 'Sales': [100, 200, 300]}
df = pd.DataFrame(data)

# Setting an index
df.set_index('City', inplace=True)

print('DataFrame after Setting Index:\n', df)

# Resetting the index
df.reset_index(inplace=True)

print('DataFrame after Resetting Index:\n', df)