# -*- coding: utf-8 -*-
"""StackingAndUnstackingDataFrames.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QtIsG_hUyQVIxCYot93A3DHS_wCilAat
"""

# Stacking and Unstacking DataFrames
import pandas as pd

# Creating a DataFrame
data = {'City': ['NY', 'LA'], '2020': [100, 150], '2021': [200, 250]}
df = pd.DataFrame(data).set_index('City')

# Stacking and unstacking the DataFrame
stacked_df = df.stack()
unstacked_df = stacked_df.unstack()

print('Stacked DataFrame:\n', stacked_df)
print('Unstacked DataFrame:\n', unstacked_df)