# -*- coding: utf-8 -*-
"""UsingQueryWithVariables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QtIsG_hUyQVIxCYot93A3DHS_wCilAat
"""

# Using query() with Variables
import pandas as pd

# Creating a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Score': [85, 70, 95]}
df = pd.DataFrame(data)

# Using query() with variables
threshold = 80
filtered_df = df.query('Score > @threshold')

print('Filtered DataFrame with query() and Variables:\n', filtered_df)