# -*- coding: utf-8 -*-
"""UsingshiftForTimeSeries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QtIsG_hUyQVIxCYot93A3DHS_wCilAat
"""

# Using shift() for Time Series Analysis
import pandas as pd

# Creating a time series DataFrame
date_range = pd.date_range(start='2023-01-01', periods=5, freq='D')
data = {'Sales': [200, 250, 300, 350, 400]}
df = pd.DataFrame(data, index=date_range)

# Shifting the data to create a lag
df['Previous Day Sales'] = df['Sales'].shift(1)

print('DataFrame with Shifted Time Series Data:\n', df)